# boost_nested_exception_example
Boost nested exception example usage
